### PR TITLE
FIX: A bunch of cases, more tests

### PR DESCRIPTION
**Pull request by CvX**
Fixed some cases, including:

```markdown
[*] hello
[*] hello
```

### CODE REVIEW

**Comment by SamSaffron** [comment]
Fixes super welcome merge at will :confetti_ball:

**Comment by SamSaffron** [comment]
give the regex fiddling, can you test on local if there is any performance impact on very large documents? 

I would recommend testing 1 giant line, and say 50000 chars to see that neither suffer.

**Comment by CvX** [comment]
On-click performance is roughly the same, and markdown processing:

* is difficult to precisely measure and compare because instead of a single `processChecklist` call we now have 200 (in my test case) calls to process and postprocess functions that are largely reporting 0.001ms execution time which is the lower precision limit, i.e. those calls most likely are faster but their time is rounded up
* that being said, there is a performance impact somewhere between 2x and 4x
* but it's a difference between 0.35ms and 1.4ms (on max length posts with hundreds of checkboxes) and it's a cost that will be paid only on initial render after #22 is merged, and when we drop the support for more unusual syntax (e.g. `[-]`) we'll save some execution time there too 🙂

**Comment by SamSaffron** [comment]
Should we close this? @coding-horror's call is that we are going to just junk support for `[*]` anyway

**Comment by ZogStriP** [comment]
@CvX do we need this considering we're working on #23? 

Are there any goodies in this PR we should keep?

**Comment by CvX** [comment]
Closing. I'll open a new one when the dust settles (i.e. after #23 is merged 😉)

**Pull request closed without merging**
